apiVersion: v1
kind: Secret
metadata:
  name: ssh-key
  annotations:
    tekton.dev/git-0: gitlab.example.com
type: kubernetes.io/ssh-auth
stringData:
  ssh-privatekey: | 
    -----BEGIN RSA PRIVATE KEY-----
    FIXME
    -----END RSA PRIVATE KEY-----
