kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pipeline-task-cache-pvc
spec:
  storageClassName: ocs-storagecluster-ceph-rbd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
